version: '3.9'

services:
  setup:
    build:
      context: .
      dockerfile: setup.Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    entrypoint: ["bash"]
    stdin_open: true
    tty: true
